### PR TITLE
Switch Android to using `KHR_vulkan_enable2`

### LINKED ISSUE #408: [Bug] Crash when using RenderDoc Meta Fork v44.1
## Background

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NulError(19, [86, 75, 95, 69, 88, 84, 95, 100, 101, 98, 117, 103, 95, 109, 97, 114, 107, 101, 114, 0, 70])', C:\Users\kanem\Development\hotham\hotham\src\contexts\vulkan_context.rs:998:34
```

### PR DESCRIPTION
**Pull request by kanerogers**
Closes #408 

Would be good to (re-implement) support for this in the simulator at some point.

### CODE REVIEW

**Comment by kanerogers** [comment]
Merging this one in as it's just a bugfix. Confirmed working on headset and simulator.

File: hotham/src/contexts/vulkan_context.rs [hunk 1]
```diff
@@ -894,12 +908,7 @@ fn vulkan_init_legacy(
     unsafe {
         let entry = Entry::new()?;
 
-        #[cfg(debug_assertions)]
-        let layers = vec!["VK_LAYER_KHRONOS_validation\0"];
```
Comment (rasmusgo) [inline hotham/src/contexts/vulkan_context.rs:898]: Are we never using validation layers now?
